-- Access audit: board unlock events for accountability (V3 WS-A8).

ALTER TABLE audit_events DROP CONSTRAINT IF EXISTS audit_events_event_type_check;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_event_type_check
  CHECK (
    event_type IN (
      'PERSON_CREATED',
      'PERSON_UPDATED',
      'PERSON_STATUS_CHANGED',
      'PERSON_ARCHIVED',
      'PERSON_RESTORED',
      'PERSON_MERGED',
      'CONTACT_METHOD_ADDED',
      'CONTACT_METHOD_UPDATED',
      'LOCATION_CREATED',
      'LOCATION_UPDATED',
      'LOCATION_CODE_CHANGED',
      'TEAM_ASSIGNMENT_CREATED',
      'TEAM_ASSIGNMENT_UPDATED',
      'TEAM_ASSIGNMENT_ENDED',
      'TEAM_TASK_CREATED',
      'TEAM_TASK_UPDATED',
      'TEAM_TASK_COMPLETED',
      'TEAM_RESOURCE_CREATED',
      'TEAM_RESOURCE_UPDATED',
      'TEAM_RESOURCE_ARCHIVED',
      'PIPELINE_TAG_ADDED',
      'PIPELINE_TAG_REMOVED',
      'ROLE_GRANTED',
      'ROLE_REVOKED',
      'BETA_FEEDBACK_SUBMITTED',
      'APPLICATION_SUBMITTED',
      'APPLICATION_UPDATED',
      'APPLICATION_ACCEPTED',
      'APPLICATION_DECLINED',
      'CALENDAR_EVENT_CREATED',
      'CALENDAR_EVENT_UPDATED',
      'CALENDAR_EVENT_CANCELLED',
      'CALENDAR_RSVP_INVITED',
      'CALENDAR_RSVP_UPDATED',
      'CALENDAR_RSVP_REMOVED',
      'CALENDAR_OCCURRENCE_CANCELLED',
      'ACCOUNT_INVITED',
      'ACCOUNT_CLAIMED',
      'ACCOUNT_LOGIN',
      'ACCOUNT_DISABLED',
      'BOARD_UNLOCKED',
      'PROFILE_UPDATED',
      'PROFILE_PHOTO_UPDATED',
      'PROFILE_NOTE_CREATED',
      'PROFILE_NOTE_ARCHIVED'
    )
  );

CREATE INDEX IF NOT EXISTS audit_events_access_types_idx
  ON audit_events (created_at DESC)
  WHERE event_type IN (
    'BOARD_UNLOCKED',
    'ACCOUNT_LOGIN',
    'ACCOUNT_CLAIMED',
    'ACCOUNT_INVITED',
    'APPLICATION_ACCEPTED',
    'APPLICATION_DECLINED',
    'ROLE_GRANTED',
    'ROLE_REVOKED'
  );
